# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module GmailApi

  class Configuration
    # The base Uri for API calls
    @base_uri = 'https://www.googleapis.com/gmail/v1/users'

    # The OAuth 2.0 access token to be set before API calls
    @o_auth_access_token = 'TODO: Replace'

    # The attribute accessors for public properties
    class << self
      attr_accessor :base_uri
      attr_accessor :o_auth_access_token
    end
 
  end
end
