# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module GmailApi
  class GmailAPIClient
    # Singleton access to users controller
    # @return [UsersController] Returns the controller instance
    def users
      UsersController.instance
    end

    # Singleton access to threads controller
    # @return [ThreadsController] Returns the controller instance
    def threads
      ThreadsController.instance
    end

    # Singleton access to messages controller
    # @return [MessagesController] Returns the controller instance
    def messages
      MessagesController.instance
    end

    # Singleton access to attachments controller
    # @return [AttachmentsController] Returns the controller instance
    def attachments
      AttachmentsController.instance
    end

    # Singleton access to labels controller
    # @return [LabelsController] Returns the controller instance
    def labels
      LabelsController.instance
    end

    # Singleton access to history controller
    # @return [HistoryController] Returns the controller instance
    def history
      HistoryController.instance
    end

    # Singleton access to drafts controller
    # @return [DraftsController] Returns the controller instance
    def drafts
      DraftsController.instance
    end

    # Initializer with authentication and configuration parameters
    def initialize(o_auth_access_token: nil)
      Configuration.o_auth_access_token = o_auth_access_token if o_auth_access_token
    end
  end
end
