# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module GmailApi
  class Draft < BaseModel
    # The immutable ID of the draft.
    # @return [String]
    attr_accessor :id

    # The message content of the draft.
    # @return [Message]
    attr_accessor :message

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["id"] = "id"
        @hash["message"] = "message"
      end
      @hash
    end

    def initialize(id = nil,
                   message = nil)
      @id = id
      @message = message
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        id = hash["id"]
        message = Message.from_hash(hash["message"]) if hash["message"]

        # Create object from extracted values
        Draft.new(id,
                  message)
      end
    end
  end
end
