# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module GmailApi
  class HistoryMessageAdded < BaseModel
    # An email message.
    # @return [Message]
    attr_accessor :message

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["message"] = "message"
      end
      @hash
    end

    def initialize(message = nil)
      @message = message
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        message = Message.from_hash(hash["message"]) if hash["message"]

        # Create object from extracted values
        HistoryMessageAdded.new(message)
      end
    end
  end
end
