# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module GmailApi
  class LabelListVisibilityEnum
    # TODO: Write general description for LABELHIDE
    # TODO: Write general description for LABELSHOW
    # TODO: Write general description for LABELSHOWIFUNREAD
    LABEL_LIST_VISIBILITY_ENUM = [LABELHIDE = 'labelHide', LABELSHOW = 'labelShow', LABELSHOWIFUNREAD = 'labelShowIfUnread']
  end
end