# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module GmailApi
  class LabelFilterActionEnum
    # TODO: Write general description for EXCLUDE
    # TODO: Write general description for INCLUDE
    LABEL_FILTER_ACTION_ENUM = [EXCLUDE = 'exclude', INCLUDE = 'include']
  end
end