# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module GmailApi
  class Label < BaseModel
    # The immutable ID of the label.
    # @return [String]
    attr_accessor :id

    # The visibility of the label in the label list in the Gmail web interface.
    # @return [LabelListVisibilityEnum]
    attr_accessor :label_list_visibility

    # The visibility of the label in the message list in the Gmail web interface.
    # @return [MessageListVisibilityEnum]
    attr_accessor :message_list_visibility

    # The total number of messages with the label.
    # @return [Integer]
    attr_accessor :messages_total

    # The number of unread messages with the label.
    # @return [Integer]
    attr_accessor :messages_unread

    # The display name of the label.
    # @return [String]
    attr_accessor :name

    # The total number of threads with the label.
    # @return [Integer]
    attr_accessor :threads_total

    # The number of unread threads with the label.
    # @return [Integer]
    attr_accessor :threads_unread

    # The owner type for the label. User labels are created by the user and can be modified and deleted by the user and can be applied to any message or thread. System labels are internally created and cannot be added, modified, or deleted. System labels may be able to be applied to or removed from messages and threads under some circumstances but this is not guaranteed. For example, users can apply and remove the INBOX and UNREAD labels from messages and threads, but cannot apply or remove the DRAFTS or SENT labels from messages or threads.
    # @return [TypeEnum]
    attr_accessor :type

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["id"] = "id"
        @hash["label_list_visibility"] = "labelListVisibility"
        @hash["message_list_visibility"] = "messageListVisibility"
        @hash["messages_total"] = "messagesTotal"
        @hash["messages_unread"] = "messagesUnread"
        @hash["name"] = "name"
        @hash["threads_total"] = "threadsTotal"
        @hash["threads_unread"] = "threadsUnread"
        @hash["type"] = "type"
      end
      @hash
    end

    def initialize(id = nil,
                   label_list_visibility = nil,
                   message_list_visibility = nil,
                   messages_total = nil,
                   messages_unread = nil,
                   name = nil,
                   threads_total = nil,
                   threads_unread = nil,
                   type = nil)
      @id = id
      @label_list_visibility = label_list_visibility
      @message_list_visibility = message_list_visibility
      @messages_total = messages_total
      @messages_unread = messages_unread
      @name = name
      @threads_total = threads_total
      @threads_unread = threads_unread
      @type = type
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        id = hash["id"]
        label_list_visibility = hash["labelListVisibility"]
        message_list_visibility = hash["messageListVisibility"]
        messages_total = hash["messagesTotal"]
        messages_unread = hash["messagesUnread"]
        name = hash["name"]
        threads_total = hash["threadsTotal"]
        threads_unread = hash["threadsUnread"]
        type = hash["type"]

        # Create object from extracted values
        Label.new(id,
                  label_list_visibility,
                  message_list_visibility,
                  messages_total,
                  messages_unread,
                  name,
                  threads_total,
                  threads_unread,
                  type)
      end
    end
  end
end
