# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module GmailApi
  class ListMessagesResponse < BaseModel
    # List of messages.
    # @return [List of Message]
    attr_accessor :messages

    # Token to retrieve the next page of results in the list.
    # @return [String]
    attr_accessor :next_page_token

    # Estimated total number of results.
    # @return [Integer]
    attr_accessor :result_size_estimate

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["messages"] = "messages"
        @hash["next_page_token"] = "nextPageToken"
        @hash["result_size_estimate"] = "resultSizeEstimate"
      end
      @hash
    end

    def initialize(messages = nil,
                   next_page_token = nil,
                   result_size_estimate = nil)
      @messages = messages
      @next_page_token = next_page_token
      @result_size_estimate = result_size_estimate
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        # Parameter is an array, so we need to iterate through it
        messages = nil
        if hash["messages"] != nil
          messages = Array.new
          hash["messages"].each{|structure| messages << (Message.from_hash(structure) if structure)}
        end
        next_page_token = hash["nextPageToken"]
        result_size_estimate = hash["resultSizeEstimate"]

        # Create object from extracted values
        ListMessagesResponse.new(messages,
                                 next_page_token,
                                 result_size_estimate)
      end
    end
  end
end
