# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module GmailApi
  class ListDraftsResponse < BaseModel
    # List of drafts.
    # @return [List of Draft]
    attr_accessor :drafts

    # Token to retrieve the next page of results in the list.
    # @return [String]
    attr_accessor :next_page_token

    # Estimated total number of results.
    # @return [Integer]
    attr_accessor :result_size_estimate

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["drafts"] = "drafts"
        @hash["next_page_token"] = "nextPageToken"
        @hash["result_size_estimate"] = "resultSizeEstimate"
      end
      @hash
    end

    def initialize(drafts = nil,
                   next_page_token = nil,
                   result_size_estimate = nil)
      @drafts = drafts
      @next_page_token = next_page_token
      @result_size_estimate = result_size_estimate
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        # Parameter is an array, so we need to iterate through it
        drafts = nil
        if hash["drafts"] != nil
          drafts = Array.new
          hash["drafts"].each{|structure| drafts << (Draft.from_hash(structure) if structure)}
        end
        next_page_token = hash["nextPageToken"]
        result_size_estimate = hash["resultSizeEstimate"]

        # Create object from extracted values
        ListDraftsResponse.new(drafts,
                               next_page_token,
                               result_size_estimate)
      end
    end
  end
end
