# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module GmailApi
  class ListHistoryResponse < BaseModel
    # List of history records. Any messages contained in the response will typically only have id and threadId fields populated.
    # @return [List of History]
    attr_accessor :history

    # The ID of the mailbox's current history record.
    # @return [String]
    attr_accessor :history_id

    # Page token to retrieve the next page of results in the list.
    # @return [String]
    attr_accessor :next_page_token

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["history"] = "history"
        @hash["history_id"] = "historyId"
        @hash["next_page_token"] = "nextPageToken"
      end
      @hash
    end

    def initialize(history = nil,
                   history_id = nil,
                   next_page_token = nil)
      @history = history
      @history_id = history_id
      @next_page_token = next_page_token
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        # Parameter is an array, so we need to iterate through it
        history = nil
        if hash["history"] != nil
          history = Array.new
          hash["history"].each{|structure| history << (History.from_hash(structure) if structure)}
        end
        history_id = hash["historyId"]
        next_page_token = hash["nextPageToken"]

        # Create object from extracted values
        ListHistoryResponse.new(history,
                                history_id,
                                next_page_token)
      end
    end
  end
end
