# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module GmailApi
  class ListLabelsResponse < BaseModel
    # List of labels.
    # @return [List of Label]
    attr_accessor :labels

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["labels"] = "labels"
      end
      @hash
    end

    def initialize(labels = nil)
      @labels = labels
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        # Parameter is an array, so we need to iterate through it
        labels = nil
        if hash["labels"] != nil
          labels = Array.new
          hash["labels"].each{|structure| labels << (Label.from_hash(structure) if structure)}
        end

        # Create object from extracted values
        ListLabelsResponse.new(labels)
      end
    end
  end
end
