# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module GmailApi
  class MessageListVisibilityEnum
    # TODO: Write general description for HIDE
    # TODO: Write general description for SHOW
    MESSAGE_LIST_VISIBILITY_ENUM = [HIDE = 'hide', SHOW = 'show']
  end
end