# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module GmailApi
  class MessagePartHeader < BaseModel
    # The name of the header before the : separator. For example, To.
    # @return [String]
    attr_accessor :name

    # The value of the header after the : separator. For example, someuser@example.com.
    # @return [String]
    attr_accessor :value

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["name"] = "name"
        @hash["value"] = "value"
      end
      @hash
    end

    def initialize(name = nil,
                   value = nil)
      @name = name
      @value = value
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        name = hash["name"]
        value = hash["value"]

        # Create object from extracted values
        MessagePartHeader.new(name,
                              value)
      end
    end
  end
end
