# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module GmailApi
  class MessagePartBody < BaseModel
    # When present, contains the ID of an external attachment that can be retrieved in a separate messages.attachments.get request. When not present, the entire content of the message part body is contained in the data field.
    # @return [String]
    attr_accessor :attachment_id

    # The body data of a MIME message part. May be empty for MIME container types that have no message body or when the body data is sent as a separate attachment. An attachment ID is present if the body data is contained in a separate attachment.
    # @return [String]
    attr_accessor :data

    # Total number of bytes in the body of the message part.
    # @return [Integer]
    attr_accessor :size

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["attachment_id"] = "attachmentId"
        @hash["data"] = "data"
        @hash["size"] = "size"
      end
      @hash
    end

    def initialize(attachment_id = nil,
                   data = nil,
                   size = nil)
      @attachment_id = attachment_id
      @data = data
      @size = size
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        attachment_id = hash["attachmentId"]
        data = hash["data"]
        size = hash["size"]

        # Create object from extracted values
        MessagePartBody.new(attachment_id,
                            data,
                            size)
      end
    end
  end
end
