# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module GmailApi
  class ModifyThreadRequest < BaseModel
    # A list of IDs of labels to add to this thread.
    # @return [List of String]
    attr_accessor :add_label_ids

    # A list of IDs of labels to remove from this thread.
    # @return [List of String]
    attr_accessor :remove_label_ids

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["add_label_ids"] = "addLabelIds"
        @hash["remove_label_ids"] = "removeLabelIds"
      end
      @hash
    end

    def initialize(add_label_ids = nil,
                   remove_label_ids = nil)
      @add_label_ids = add_label_ids
      @remove_label_ids = remove_label_ids
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        add_label_ids = hash["addLabelIds"]
        remove_label_ids = hash["removeLabelIds"]

        # Create object from extracted values
        ModifyThreadRequest.new(add_label_ids,
                                remove_label_ids)
      end
    end
  end
end
