# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module GmailApi
  class Profile < BaseModel
    # The user's email address.
    # @return [String]
    attr_accessor :email_address

    # The ID of the mailbox's current history record.
    # @return [String]
    attr_accessor :history_id

    # The total number of messages in the mailbox.
    # @return [Integer]
    attr_accessor :messages_total

    # The total number of threads in the mailbox.
    # @return [Integer]
    attr_accessor :threads_total

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["email_address"] = "emailAddress"
        @hash["history_id"] = "historyId"
        @hash["messages_total"] = "messagesTotal"
        @hash["threads_total"] = "threadsTotal"
      end
      @hash
    end

    def initialize(email_address = nil,
                   history_id = nil,
                   messages_total = nil,
                   threads_total = nil)
      @email_address = email_address
      @history_id = history_id
      @messages_total = messages_total
      @threads_total = threads_total
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        email_address = hash["emailAddress"]
        history_id = hash["historyId"]
        messages_total = hash["messagesTotal"]
        threads_total = hash["threadsTotal"]

        # Create object from extracted values
        Profile.new(email_address,
                    history_id,
                    messages_total,
                    threads_total)
      end
    end
  end
end
