# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module GmailApi
  class TypeEnum
    # TODO: Write general description for SYSTEM
    # TODO: Write general description for USER
    TYPE_ENUM = [SYSTEM = 'system', USER = 'user']
  end
end