# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module GmailApi
  class WatchResponse < BaseModel
    # When Gmail will stop sending notifications for mailbox updates (epoch millis). Call watch again before this time to renew the watch.
    # @return [String]
    attr_accessor :expiration

    # The ID of the mailbox's current history record.
    # @return [String]
    attr_accessor :history_id

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["expiration"] = "expiration"
        @hash["history_id"] = "historyId"
      end
      @hash
    end

    def initialize(expiration = nil,
                   history_id = nil)
      @expiration = expiration
      @history_id = history_id
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        expiration = hash["expiration"]
        history_id = hash["historyId"]

        # Create object from extracted values
        WatchResponse.new(expiration,
                          history_id)
      end
    end
  end
end
